package ru.gribbirg.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme

internal val lightColorSchemeImpl = lightColorScheme(
    primary = LightBlue,
    onPrimary = White,
    primaryContainer = LightPrimaryBack,
    onPrimaryContainer = LightPrimaryLabel,
    inversePrimary = Black,
    secondary = LightGreen,
    onSecondary = White,
    secondaryContainer = LightSecondaryBack,
    onSecondaryContainer = LightSecondaryBack,
    tertiary = LightRed,
    onTertiary = White,
    tertiaryContainer = LightGray,
    onTertiaryContainer = LightTertiaryLabel,
    background = LightPrimaryBack,
    onBackground = LightPrimaryLabel,
    surface = LightGray,
    onSurface = LightGrayLight,
    surfaceVariant = LightGrayLight,
    onSurfaceVariant = White,
    surfaceTint = LightBlue,
    inverseSurface = DarkGrayLight,
    inverseOnSurface = DarkGrayLight,
    error = LightRed,
    onError = White,
    errorContainer = White,
    onErrorContainer = LightRed,
    outline = LightOverlay,
    outlineVariant = LightGrayLight,
    scrim = White,
    surfaceBright = LightGrayLight,
    surfaceContainer = LightGray,
    surfaceContainerHigh = LightGrayLight,
    surfaceContainerHighest = White,
    surfaceContainerLow = LightGray,
    surfaceContainerLowest = LightGray,
    surfaceDim = Black,
)

internal val darkColorSchemeImpl = darkColorScheme(
    primary = DarkBlue,
    onPrimary = Black,
    primaryContainer = DarkPrimaryBack,
    onPrimaryContainer = DarkPrimaryLabel,
    inversePrimary = White,
    secondary = DarkGreen,
    onSecondary = Black,
    secondaryContainer = DarkSecondaryBack,
    onSecondaryContainer = DarkSecondaryBack,
    tertiary = DarkRed,
    onTertiary = Black,
    tertiaryContainer = DarkGray,
    onTertiaryContainer = DarkTertiaryLabel,
    background = DarkPrimaryBack,
    onBackground = DarkPrimaryLabel,
    surface = DarkGray,
    onSurface = DarkGrayLight,
    surfaceVariant = DarkGrayLight,
    onSurfaceVariant = Black,
    surfaceTint = DarkBlue,
    inverseSurface = LightGrayLight,
    inverseOnSurface = LightGrayLight,
    error = DarkRed,
    onError = Black,
    errorContainer = Black,
    onErrorContainer = DarkRed,
    outline = DarkOverlay,
    outlineVariant = DarkGrayLight,
    scrim = Black,
    surfaceBright = DarkGrayLight,
    surfaceContainer = DarkGray,
    surfaceContainerHigh = DarkGrayLight,
    surfaceContainerHighest = Black,
    surfaceContainerLow = DarkGray,
    surfaceContainerLowest = DarkGray,
    surfaceDim = White,
)